POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hZ2EuOTNAYW9sLmNvbSIsImV4cCI6MTcxNzIyNzE1OSwidXNlcklkIjowfQ.d02tJi_e3MW4Lq-aHmY2DZvEtZosD-eEiaLZdvpsrvY

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}